### ISSUE TITLE
Automate Manual Checklist

### ISSUE THREAD

**Issue by mitchmikusek** [spinningarrow/up#1]
Can't we automate some of these with scripts such as:

_Trackpad: enable tap to click for this user and for the login screen_
```
  defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
  defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
  defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1;ok
```

**Comment by spinningarrow** [comment]
You're right, there's a plethora of `defaults write` commands here - https://github.com/mathiasbynens/dotfiles/blob/master/.macos.

I prefer to keep the manual stuff as a checklist instead because I like to know where Apple has the settings in the GUI (they have a tendency to move them around between macOS versions) and also because some of the settings get removed between versions.
